### PR TITLE
TestMemoryCallbacksRealServer failing

### PR DESCRIPTION
**Pull request by solomonchild**
Memory test failing when `ENABLE_UNICODE` is `OFF`. Solution: use `StrDupA`/`LocalFree` instead of `strdup`/`free`. 
Didn't change `malloc`s in the `schannel.c` though (we didn't patch those in `bidstack` too: https://github.com/bidstack-group/curl/blob/bidstack/lib/vtls/schannel.c), should I?
Also, I don't know if `ENABLE_UNICODE` branch should be fixed now or whenever we decide to use `ENABLE_UNICODE`?

Failing build:
https://dev.azure.com/bidstack/bidstack-cpp-sdk/_build/results?buildId=18392&view=logs&j=070d47b6-0f95-58e9-0f6c-2e08699c6fb5&t=ca4e29bc-3ffe-579e-1703-ae2166e85103

Interesting that it's only the debug build that's failing 🤔 am I missing something?

### CODE REVIEW

**Comment by arvids-kokins-bidstack** [comment]
I don't see how the failing build is related to these changes

the only error seems to be `D:\a\1\s\src\unit-tests\test_memory.cc(466): error: Value of: wait_for(fetch_completed)` which can be random

EDIT: try increasing the wait timeout to see if the issue goes away, a huge creative has been added to the list some time ago

EDIT 2:

> Didn't change mallocs in the schannel.c though (we didn't patch those in bidstack too: https://github.com/bidstack-group/curl/blob/bidstack/lib/vtls/schannel.c), should I?

"malloc"/"free" etc. are replaced using a macro inside curl, nothing needs to be done there 🤔
same for any other allocations that have no restrictions preventing them from using our allocation functions

**Comment by solomonchild** [comment]
@arvids-kokins-bidstack that's interesting. I didn't even look into CI logs, since I've got this locally (changing timeout doesn't help):
[memtest-log.txt](https://drive.google.com/file/d/1eiPc-FJPrRdcQ2zBp91BIorfhMvZKcGO/view?usp=sharing)

I've pushed the timeout increase to the branch.

EDIT: also seems like CI does check out the correct commit:
```
2021-04-13T12:09:27.8313516Z Submodule path 'third-party/curl': checked out '68b634cdedea616153c43633b410cab3ffde3f0e'
```
image

**Comment by arvids-kokins-bidstack** [comment]
> [memtest-log.txt](https://drive.google.com/file/d/1eiPc-FJPrRdcQ2zBp91BIorfhMvZKcGO/view?usp=sharing)

ah, that's something else indeed

is it the same when enabling unicode? generally we would prefer to enable it though I'm not sure exactly which functions this would affect (or why we haven't seen issues if it was disabled)

**Comment by solomonchild** [comment]
> is it the same when enabling unicode?

Seems so:

[memtest_unicode.txt](https://drive.google.com/file/d/1LZ-SLLx_mOvWW1rzdQIMkswdojCpVdn8/view?usp=sharing)

> or why we haven't seen issues if it was disabled

Maybe because there were no CRT allocation functions used? https://github.com/bidstack-group/curl/blob/125c1a8324e1f90c506a4e76b12f5c04432495b9/lib/curl_multibyte.h#L74
In the `bidstack-7_76_0`, there are `strdup`/`free` in the branch where UNICODE is false: 
https://github.com/bidstack-group/curl/blob/68b634cdedea616153c43633b410cab3ffde3f0e/lib/curl_multibyte.h#L67

**Comment by arvids-kokins-bidstack** [comment]
> Maybe because there were no CRT allocation functions used?

sorry, I was actually referring to using unicode instead of some windows code page for text encoding, not the allocation issue

anyway, it would be good to start using the unicode build, and pass the allocations through the regular macros

I wonder if there's a better explanation than https://github.com/curl/curl/pull/6602#issuecomment-779045099 somewhere as to why they stopped using macros in the first place - this one doesn't look particularly relevant to us

**Review by arvids-kokins-bidstack — APPROVED** [review]

**Pull request merged**
